# introduction to Numpy

In [2]:
# why numpy is better than list ?
# same data type ===> Array
# memory consume ==> Numpy less, list high
# computation power ==> numpy high, list less
# functions ==> numpy high, listless

In [3]:
import numpy as np

In [5]:
a = [1,23,78,90]
type(a)

list

In [8]:
b = np.array(a)
type(b)
b

array([ 1, 23, 78, 90])

In [13]:
List = []
length = int(input("Enter the number of element in list : "))
for i in range(length):
    data = input(f"Enter element {i} :")
    List.append(data)
# print(List)2
print(np.array(List))

Enter the number of element in list : 12
Enter element 0 :365
Enter element 1 :6652
Enter element 2 :95
Enter element 3 :55
Enter element 4 :565
Enter element 5 :35
Enter element 6 :2
Enter element 7 :2
Enter element 8 :1
Enter element 9 :22
Enter element 10 :2
Enter element 11 :2
['365' '6652' '95' '55' '565' '35' '2' '2' '1' '22' '2' '2']


## How to check shape and size of an array

In [14]:
#shape = n(rows), n(columns)

#size = total_elements ===> n(rows)*n(columns)

In [15]:
print('Total Shape = ' , b.shape)
print('Total Size = ' , b.size)

Total Shape =  (4,)
Total Size =  4


In [18]:
a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print('Total Shape = ' , b.shape)
print('Total Size = ' , b.size)

Total Shape =  (3, 3)
Total Size =  9


In [20]:
# Image ==> pixels ==> (0-225)px ==> 0px (complete black) , 255px (complete white)

# Convert ==> grayscale Image 
# Image ==> pixels ==> Normalization (0-1) ==> 0px (complete black) , 1px (complete white)


# 0 , 1 ===> Neuron System

# Matrix ==> rows , columns

# Symmatric matrix ===> n(rows) = n(columns)
# Asymmatric matrix ===> n(rows) != n(columns)
#Diagonal Elements = [(1,1), (2,2), (3,3), ....... (n,n) ]

## (1) zeros()===> it will create an array in which all the element are zero.

In [23]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [26]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## (2) Ones() ===> it will create an array in which all the values are one. 

In [27]:
a = np.ones(3)
a

array([1., 1., 1.])

In [28]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

## (3) eye()  ===. this function will create an array in which all the diagonals are 1.

In [30]:
#Asymmatric 
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [31]:
#Symmatric 
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Assignment 1

## 1. five questions on map function.

In [36]:
#1. Write a Python program to triple all numbers in a given list of integers. Use Python map.
List = [1,2,3,4,5,6,7,8,9]
triple = list(map(lambda x: x*3,List))
print(triple)

[3, 6, 9, 12, 15, 18, 21, 24, 27]


In [49]:
# 2. Write a Python program to add three given lists using Python map .
List = [1,2,3,4,5,6,7,8,9]
List2 = [1,2,3,4,5,6,7,8,9]
add = list(map(lambda x,y: x+y,List,List2))
print(add)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [58]:
# 3. Write a Python program to listify the list of given strings individually using Python map.
string_list = ["apple", "banana", "cherry", "date", "elderberry"]
listify = list(map(list,string_list))
print(f"Listify string are : ")
for item in listify:
    print(item)

Listify string are : 
['a', 'p', 'p', 'l', 'e']
['b', 'a', 'n', 'a', 'n', 'a']
['c', 'h', 'e', 'r', 'r', 'y']
['d', 'a', 't', 'e']
['e', 'l', 'd', 'e', 'r', 'b', 'e', 'r', 'r', 'y']


In [59]:
# 4. Write a Python program to create a list containing the power of said number in bases raised to the corresponding number in the index using Python map.
power = int(input("Enter the number for power ; "))
List = [1,2,3,4,5,6,7,8,9]
expo = list(map(lambda x: x**power,List))
print(expo)

Enter the number for power ; 2
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [63]:
# 5. Write a Python program to square the elements of a list using the map() function.
List = [1,2,3,4,5,6,7,8,9]
square = list(map(lambda x: x**2,List))
print(square)


[1, 4, 9, 16, 25, 36, 49, 64, 81]


## 2. five questions on filter function.

In [68]:
# 1. Write a Python function that filters out even numbers from a list of integers using the filter function.
List = [1,2,3,4,5,6,7,8,9]
even = list(filter(lambda x: x%2==0, List))
print(even)

[2, 4, 6, 8]


In [72]:
# 2. Write a Python program that uses the filter function to extract all uppercase letters from a list of mixed-case 
#strings.
string_list = ["apple", "BANANA", "cherry", "DATE", "elderberry"]
upper_case = list(filter(lambda x: x == x.upper() , string_list))
print(upper_case)

['BANANA', 'DATE']


In [74]:
# 3. Write a Python function that filters out all elements less than or equal than a specified value from a list of 
#numbers using the filter function.
spe_val = int(input("Enter a number to get less or equal to that number : "))
List = [1,2,3,4,5,6,7,8,9]
less_or_equal = list(filter(lambda x: x<=spe_val, List))
print(less_or_equal)

Enter a number to get less or equal to that number : 3
[1, 2, 3]


In [95]:
# 4. Write a Python program that creates a list of names and uses the filter function to extract names that 
# start with a vowel (A, E, I, O, U).
string_list = ["apple", "banana", "cherry", "date", "elderberry"]
vowel_name = list(filter(lambda x: x[0]=='a' or x[0]=='e' or x[0]=='i' or x[0]=='o' or x[0]=='u', string_list))
print(vowel_name)

['apple', 'elderberry']


In [99]:
# 5. Write a Python function that filters out all empty strings from a list of strings using the filter function.
string_list = ["apple", "banana", '', "cherry", "date", '', "elderberry"]
vowel_name = list(filter(lambda x: x!='', string_list))
print(vowel_name)

['apple', 'banana', 'cherry', 'date', 'elderberry']


## 3. five questions on lambda function.

In [100]:
# 1. Write a  Python program to create a lambda function that adds 15 to a given number passed in as an argument, 
add_15 = lambda x : x + 15
print(add_15(10))

25


In [102]:
# 2. create a lambda function that multiplies argument x with argument y and prints the result.
mul_x_with_y = lambda x, y : x * y
print(mul_x_with_y(2,4))

8


In [108]:
# 3. Write a  Python program to create a function that takes one argument, and that argument will be multiplied with
# an unknown given number.
unknown_number = 15
mul = lambda x: x * unknown_number
print(mul(int(input("Enter a number : "))))

Enter a number : 3
45


In [116]:
# 4. Write a python to count element in list using lambda
string_list = ["apple", "banana", "cherry", "date", "elderberry"]

count_elements = lambda lst: len(lst)

result = count_elements(string_list)

print(f"Number of elements in the list: {result}")


Number of elements in the list: 5


In [131]:
# 5. add 5 to each element of list
List = [1,2,3,4,5]
add_5 = lambda x : x+5
for i in List:
    print(add_5(i))

6
7
8
9
10


## 4. Do practice of different matrixes

In [133]:
import numpy as n
print(n.zeros(3))

[0. 0. 0.]


In [135]:
print(n.ones(4))

[1. 1. 1. 1.]


In [139]:
print(n.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [140]:
print(n.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [141]:
print(n.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [142]:
print(n.eye(3,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


# Lecture_2

## 4. diag ==. This function create a two dimensional array with all the diagonal elements as the given value and rest are zero.

In [3]:
import numpy as np
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

## 5. randint ==> This function is used to generate a random number between a given range. syntax ==> randint(min_value, max_value, total no)

In [5]:
a = np.random.randint(1,10,3)
a

array([3, 5, 4])

## 6. rand() ==> This function is used to generate a random number between 0 and 1.     syntax ==> rand(number of values)

In [12]:
a = np.random.rand(3)
a

array([0.50991405, 0.91616706, 0.66771238])

## 7. randn() ==> this function is used to generate a random number from -3 to close 3. This may return positive or negative numbers as well.  Syntax ==> random.randn (number of values)

In [14]:
a = np.random.randn(3)
a

array([-0.16597783, -0.47444677,  1.43383382])

# Reshaping data

In [16]:
a = np.random.randint(1,50,12)
a

array([14, 49, 43, 46, 14, 30,  6, 15,  7, 16, 45,  5])

In [17]:
#n(rows)*n(columns) = n(total_element)

In [18]:
a.shape

(12,)

In [19]:
a = a.reshape(2,6)

In [20]:
a = a.reshape(6,2)

In [22]:
a = a.reshape(3,4)

In [106]:
# make matrix of 64 and reshape it 
a = np.random.randint(1,50,64)
num = 64
factor=[]
for fac in range(1,num+1):
    if num%fac==0:
        print(a.reshape(-1,num))


[[10 34 15 26  7  9 34 24  4 36 10 14 21 29 36 25 21 21  7 22 13  5 44 15
  41 34 39 37 38 22 41 46 48 25 30 24 40 27 44 40 43 25 47 30 24 32  3 21
  42  3 47 21  9 41 34 49 46 32 31 49 17 22  5  8]]
[[10 34 15 26  7  9 34 24  4 36 10 14 21 29 36 25 21 21  7 22 13  5 44 15
  41 34 39 37 38 22 41 46 48 25 30 24 40 27 44 40 43 25 47 30 24 32  3 21
  42  3 47 21  9 41 34 49 46 32 31 49 17 22  5  8]]
[[10 34 15 26  7  9 34 24  4 36 10 14 21 29 36 25 21 21  7 22 13  5 44 15
  41 34 39 37 38 22 41 46 48 25 30 24 40 27 44 40 43 25 47 30 24 32  3 21
  42  3 47 21  9 41 34 49 46 32 31 49 17 22  5  8]]
[[10 34 15 26  7  9 34 24  4 36 10 14 21 29 36 25 21 21  7 22 13  5 44 15
  41 34 39 37 38 22 41 46 48 25 30 24 40 27 44 40 43 25 47 30 24 32  3 21
  42  3 47 21  9 41 34 49 46 32 31 49 17 22  5  8]]
[[10 34 15 26  7  9 34 24  4 36 10 14 21 29 36 25 21 21  7 22 13  5 44 15
  41 34 39 37 38 22 41 46 48 25 30 24 40 27 44 40 43 25 47 30 24 32  3 21
  42  3 47 21  9 41 34 49 46 32 31 49 17 22  5  8]]


## principal of -1

In [102]:
# if we don't know either row or col replace it by -1
a = a.reshape(4,-1)
a

array([[46,  6, 15, 32, 25,  7, 14, 44, 23,  5, 36, 30, 40, 10, 43, 20],
       [34, 39, 25, 38,  5, 18, 11, 44, 12, 40, 25, 40, 42, 15, 29,  7],
       [31, 46, 31, 30,  9, 28,  1,  2, 10, 13,  4, 37, 46, 38,  6,  6],
       [33, 34, 45, 33,  8, 35, 44, 15, 42,  8, 12, 41, 43, 28, 11, 43]])

## Seed Function() ==> We know that randint fuction generates random numbers. Everytime we run the program , new set of random number is generated. So, solve this problem we will use seed function.

In [55]:
np.random.seed(11)
a = np.random.randint(1,100,10)
a

array([26, 64, 81, 92, 82, 56, 14, 77, 34, 72])

In [58]:
np.random.seed(111)
a = np.random.randint(1,500,30).reshape(6,5)
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

## view Vs copy ==> when we slice a sub-array from an array, it may be done by two ways.

In [60]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6]
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

## copy

In [62]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

## conditional selection

In [64]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [66]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [69]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [70]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

## operation on array

In [72]:
import numpy as np
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [73]:
a+2

array([3, 4, 5, 6])

In [74]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [75]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [76]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [77]:
a+b

array([[ 6,  8],
       [10, 12]])

In [78]:
b-a

array([[4, 4],
       [4, 4]])

In [79]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [80]:
a*b

array([[ 5, 12],
       [21, 32]])

In [82]:
#correct answerr for multiplication
a.dot(b)

array([[19, 22],
       [43, 50]])

In [87]:
a = np.array([10,20,30,40,50])
np.min(a)

10

In [88]:
np.max(a)

50

In [89]:
np.argmin(a)

0

In [90]:
np.argmax(a)

4

In [91]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [92]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

## Linspace() ==> This function returns value between a given range and with a same gap between consicutive elements.

In [93]:
import numpy as np
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

## np.unique(arr, return_index = True, return_counts= True)

#### return 3 array 1. the array with unique values 2. the array with respective index vvalue 3. the array with counting of frequency

In [95]:
a = np.array([10,20,30,40,10,20,50])
np.unique(a, return_index= True, return_counts= True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

## horizontal and vertical stacking

In [96]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [97]:
b

array([5, 6, 7, 8])

In [99]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
np.vstack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Assignment 2

In [107]:
# Q.1 = Write statement to import numpy?
import numpy as np

In [111]:
# Q.2 = Create an array using numpy ?
a = np.array([3,4])
a

array([3, 4])

In [113]:
# Q.3 = Create an array of 10 random integers ?
a = np.array(np.random.randint(1,100,10))
a

array([ 5, 11, 98, 12, 54, 50, 10, 49,  8, 76])

In [134]:
# Q.4 = Create an array of elements from 10-20?
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [116]:
# Q.5 = Create an array which contains value 5, 10 times ?
a = np.array(np.random.randint(5,6,10))
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [118]:
# Q.6 = Create a one dimensional array and convert that into 3*3 matrix ?
a = np.array(np.random.randint(1,100,9))
a.reshape(3,3)

array([[68, 60, 97],
       [51, 97, 76],
       [ 8, 14,  2]])

In [123]:
# Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1?
a = np.array(np.random.rand(9))
a.reshape(3,3)

array([[0.64871697, 0.24904759, 0.65890977],
       [0.90041947, 0.90756005, 0.72930591],
       [0.17499494, 0.41745292, 0.25423037]])

In [132]:
# Q.8 = Concatenate 2D array horizontally and vertically?
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
print(np.hstack((a,b)))
print()
print(np.vstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
