In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\HP\\regex2\\Machine_Learning\\Assignment_2\\covid_toy.csv")

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df=df.dropna()

In [5]:
df=df.drop(columns=['age','fever'])

In [6]:
df.head()

gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
df.shape

(90, 4)

# get_dummies

In [9]:
p=pd.get_dummies(df,columns=['gender','cough','city','has_covid'])

In [10]:
p.shape

(90, 10)

In [17]:
p

gender_Male  cough_Strong  city_Delhi  city_Kolkata  city_Mumbai  \
0             1             0           0             1            0   
1             1             0           1             0            0   
2             1             0           1             0            0   
3             0             0           0             1            0   
4             0             0           0             0            1   
..          ...           ...         ...           ...          ...   
95            0             0           0             0            0   
96            0             1           0             1            0   
97            0             0           0             0            0   
98            0             1           0             0            1   
99            0             1           0             1            0   

    has_covid_Yes  
0               0  
1               1  
2               0  
3               0  
4               0  
..            ...  
95              0  
96              1  
97              0  
98              0  
99              1  

[90 rows x 6 columns]

In [11]:
p=pd.get_dummies(df,columns=['gender','cough','city','has_covid'],drop_first=True)

In [12]:
p.shape

(90, 6)

In [13]:
ohe=OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [14]:
df_new=ohe.fit_transform(df[['gender','cough','city','has_covid']])

In [16]:
df_new.shape

(90, 6)

# column transformer

In [50]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import OrdinalEncoder

In [51]:
df=pd.read_csv("C:\\Users\\HP\\regex2\\Machine_Learning\\Assignment_2\\covid_toy.csv")

In [52]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [53]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [54]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [55]:
x_train

age  gender  fever   cough       city
24   13  Female  100.0  Strong    Kolkata
35   82  Female  102.0  Strong  Bangalore
59    6  Female  104.0    Mild    Kolkata
7    20  Female    NaN  Strong     Mumbai
34   74    Male  102.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
62   56  Female  104.0  Strong  Bangalore
11   65  Female   98.0    Mild     Mumbai
45   72    Male   99.0    Mild  Bangalore
77    8  Female  101.0    Mild    Kolkata
13   64    Male  102.0    Mild  Bangalore

[80 rows x 5 columns]

In [56]:
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [57]:
#ordinalencoder

oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

x_test_cough=oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [58]:
#Extracting Age

x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

#Also test data

x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values



In [59]:
x_train_age.shape

(80, 1)

In [60]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_cough),axis=1)

In [61]:
x_train_transformed.shape

(80, 3)

In [65]:
from sklearn.compose import ColumnTransformer

transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough') 

In [66]:
transformer.fit_transform(x_train).shape

(80, 7)

# function transformer

In [67]:
from sklearn.preprocessing import FunctionTransformer

import numpy as np

x=np.array([[1,2],[3,4]])

log_transform=FunctionTransformer(np.log1p)

x_transformed=log_transform.transform(x)

print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


# Example_2

In [68]:
from sklearn.preprocessing import FunctionTransformer

import numpy as np

x=np.array([[1,2],[3,4]])

In [69]:
def my_feature_engineering(x):
    return np.hstack((x,x**2))

custom_transformer=FunctionTransformer(my_feature_engineering)

x_transformed=custom_transformer.transform(x)

print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


# Example_3

In [70]:
from sklearn.preprocessing import FunctionTransformer

import numpy as np

x=np.array([[1,2],[3,4]])

In [71]:
def my_sacling(x):
    return x/np.max(x)

custom_transformer=FunctionTransformer(my_sacling)

x_transformed=custom_transformer.transform(x)

print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


# Example_4

In [72]:
from sklearn.preprocessing import FunctionTransformer

import numpy as np

x=np.array([[1,2],[3,np.nan]])

def my_cleaning(x):
    x[np.isnan(x)]=0
    return x

custom_transformer=FunctionTransformer(my_cleaning)

x_transformed=custom_transformer.transform(x)

print(x_transformed)


[[1. 2.]
 [3. 0.]]
